### ISSUE TITLE
Tasks for v1.32 release cycle

### ISSUE THREAD

**Issue by zhanggbj** [kubernetes/cloud-provider-vsphere#1316]
This is an umbrella issue for tasks of v1.32 release cycle

**Releases**

After K8s 1.32.0-beta.0 released (Nov 5),
- [x] [P0] Deliver CPI release to support K8s v1.32.0-beta.0 #1312 #1298
- [x] [P1] Bump CAPI v1.9.0-beta.1 & CAPV v1.12.0-beta.1 in E2E Test #1311 https://github.com/kubernetes/cloud-provider-vsphere/pull/1325

After K8s v1.32.0-rc.0 released (Nov 26),
- [x] [P0] Deliver CPI release to support K8s v1.32.0-rc.0 #1313 #1338
- [x] [P1] Bump CAPI v1.9.0 & CAPV v1.12.0-rc.1 in E2E test #1314 https://github.com/kubernetes/cloud-provider-vsphere/pull/1346

After K8s v1.32.0 released (Dec 11),
- [x] [P0] Deliver CPI release to support K8s v1.32.0 #1315 https://github.com/kubernetes/cloud-provider-vsphere/pull/1346
- [x] [P1] Bump CAPI v1.9.1 && CAPV v1.12.0 in E2E test #1317

**Comment by zhanggbj** [comment]
CC @DanielXiao @lubronzhan
